; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_staff_roll:=music_data_staff_roll

music_data_staff_roll:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : Staff Roll
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_staff_roll
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env4,@env6,@env0 ; 00 : Closed Hat
	.word @env9,@env4,@env6,@env0 ; 01 : Open Hat
	.word @env7,@env5,@env6,@env0 ; 02 : SS Noise snare(D3)

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c2,$c0,$00,$01
@env2:
	.byte $00,$bf,$7f,$00,$02
@env3:
	.byte $00,$cc,$c9,$c4,$c2,$c1,$06,$c0,$00,$07
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $c0,$c1,$c2,$00,$02
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $00,$cf,$c9,$04,$c7,$04,$c5,$04,$c3,$00,$08
@env8:
	.byte $00,$ce,$7f,$00,$02
@env9:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$00,$0e
@env10:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0d,$40,$00 ; 00 Punch Kick (Pitch:13)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$2d,$0f,$7e,$00 ; 01 snaph01 (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $ff, $ff, $ff, $bf, $48, $ff, $ff, $ff, $ff, $bf, $48, $ff, $ff, $ff, $ff, $bf, $48, $ff, $ff, $ff, $ff, $bf, $44
	.byte $00
@song0ch2:
@song0ch1:
	.byte $ff, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $ff, $bf, $44, $00
@song0ch3:
@song0ref51:
	.byte $80
@song0ref52:
	.byte $31, $83, $00, $8f
@song0ref56:
	.byte $31, $83, $00, $83
@song0ref60:
	.byte $31, $83, $00, $8f, $31, $83, $00, $83, $82, $31, $95, $80, $31, $83, $00, $83, $31, $83, $00, $8f, $31, $83, $00, $9b
	.byte $31, $83, $00, $83, $31, $83, $00, $83, $31, $83, $00, $83, $31, $83, $00, $83, $82, $31, $a1
	.byte $41, $10
	.word @song0ref51
	.byte $41, $26
	.word @song0ref60
	.byte $84, $2a, $83, $00, $8f, $80
	.byte $41, $0c
	.word @song0ref56
	.byte $41, $30
	.word @song0ref52
	.byte $41, $10
	.word @song0ref51
	.byte $41, $26
	.word @song0ref60
	.byte $84, $2a, $83, $00, $8f, $80
	.byte $41, $0c
	.word @song0ref56
	.byte $41, $30
	.word @song0ref52
	.byte $41, $10
	.word @song0ref51
	.byte $41, $26
	.word @song0ref60
	.byte $84, $2a, $83, $00, $8f, $80
	.byte $41, $0c
	.word @song0ref56
	.byte $41, $30
	.word @song0ref52
	.byte $41, $10
	.word @song0ref51
	.byte $41, $26
	.word @song0ref60
	.byte $84, $2a, $83, $00, $8f, $80
	.byte $41, $0c
	.word @song0ref56
	.byte $44, $00
@song0ch4:
	.byte $01, $95, $00, $d1, $01, $95, $00, $ad, $01, $95, $00
@song0ref186:
	.byte $ad
@song0ref187:
	.byte $01, $95, $00, $89, $01, $95, $00, $d1, $01, $95, $00, $ad, $01, $95, $00, $89, $02, $95, $00, $89
	.byte $41, $0f
	.word @song0ref187
	.byte $41, $15
	.word @song0ref186
	.byte $41, $0f
	.word @song0ref187
	.byte $41, $15
	.word @song0ref186
	.byte $41, $0f
	.word @song0ref187
	.byte $41, $15
	.word @song0ref186
	.byte $01, $95, $00, $89, $44, $00
