sfx_extralife = 0
sfx_bjump = 1
sfx_blast = 2
sfx_bows_fall = 3
sfx_brick = 4
sfx_bump = 5
sfx_coin = 6
sfx_smack = 7
sfx_stomp = 8
sfx_breath = 9
sfx_fireball = 10
sfx_flagpole = 11
sfx_grow = 12
sfx_growpu = 13
sfx_injury = 14
sfx_pause_ = 15
sfx_sjump = 16
sfx_timer = 17
sfx_vine = 18
sfx_max = 19

.if SFX_STRINGS
sfx_strings:
.asciiz "EXTRALIFE"
.asciiz "BJUMP"
.asciiz "BLAST"
.asciiz "BOWS_FALL"
.asciiz "BRICK"
.asciiz "BUMP"
.asciiz "COIN"
.asciiz "SMACK"
.asciiz "STOMP"
.asciiz "BREATH"
.asciiz "FIREBALL"
.asciiz "FLAGPOLE"
.asciiz "GROW"
.asciiz "GROWPU"
.asciiz "INJURY"
.asciiz "PAUSE_"
.asciiz "SJUMP"
.asciiz "TIMER"
.asciiz "VINE"
.endif
